server:
  port: 8004
spring:
  application:
    name: zuul8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul8004
    prefer-ip-address: true
info:
  author: zzei
  server:
    name: zuul8004
zuul:
  prefix: /                     #统一前缀
  ignored-services: "*"
  routes:
    provide:                    #路由微服务
      serviceId: provide8002    #微服务application.name 若该服务有多个，则自动采用轮询负载均衡
      path: /provide/**         #路由路径
    consumer:
      serviceId: consumer8003
      path: /consumer/**

